ucs_state: absent
#ucs_username: admin
# Protect variable with ansible-vault, here is how to make the vault string below
# ansible-vault encrypt_string --vault-id ~/.vault_pass.txt 'admin' --name 'ucs_username'
ucs_username: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35386662346637353932313362633831366633656263666539313133623631323431623166633230
          6433393734623730353866336235366439643633643637380a353866633635616631656137366633
          62333132396330343935323239366134333362396163656330626361333434316634386437363664
          6632666237376237380a373239383238313564393961666661383366663261316134313439623734
          3934
#ucs_password: password
# Protect variable with ansible-vault, here is how to make the vault string below
# ansible-vault encrypt_string --vault-id ~/.vault_pass.txt 'password' --name 'ucs_password'
ucs_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35633631356261613462636539653637343464656334393430363131303333343830313664366337
          3238636464633530656530323261323632393963663665330a646231313064613661303234396465
          66643037393934356236333733353832313366316331343464336462363939366237663965643661
          3266656335656465620a646239326233313536303939306562353239623465623233633366363465
          6338
ansible_python_interpreter: ~/projects/webhook-listener-venv/bin/python

vlans:
  - { name: 'dev', id: '1000', native: 'no' }
  - { name: 'prod', id: '1001', native: 'no' }
  - { name: 'test', id: '1002', native: 'no' }