aci_state: present
aci_username: admin
# Protect variable with ansible-vault, here is how to make the vault string below
# ansible-vault encrypt_string --vault-id ~/.vault_pass.txt 'admin' --name 'aci_username'
#aci_username: !vault |
#          $ANSIBLE_VAULT;1.1;AES256
#          33346435393939623138326139333333383036383262656538316530306466373237643432343935
#          3933616230333638663766313363613436333964393133350a666262646163653435303866633566
#          63363063303637633362616136313031646166623863646463626563333333643339633837323962
#          3031616564356436620a633463333637323539623337323339616131383035323530346666646433
#          3234
aci_password: ciscopsdt
# Protect variable with ansible-vault, here is how to make the vault string below
# ansible-vault encrypt_string --vault-id ~/.vault_pass.txt 'password' --name 'aci_password'
#aci_password: !vault |
#          $ANSIBLE_VAULT;1.1;AES256
#          65633563663939643431343631323032616634363133366230346532316530396338353062666562
#          6166636265303537396264383130663066383138393064620a363132363363613735353265326534
#          65343161316261643635666664386131353134336361363961616435373932316137653362663132
#          3932646264373066310a363061373366376163366238643666333634626261613434393963306530
#          3465
ansible_python_interpreter: ~/projects/webhook-listener-venv/bin/python

tenant_name: App_Tenant
vrf: app_vrf
bridge_domain: app_bd
gateway: "10.1.100.1"
mask: 24


